# Generated by Django 4.2.7 on 2024-04-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_chat_id_remove_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='токен'),
        ),
    ]
