# Generated by Django 4.2.7 on 2024-04-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='токен'),
        ),
    ]
