# Generated by Django 4.2.7 on 2024-04-14 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='session_id',
            new_name='payment_session_id',
        ),
    ]
