# Generated by Django 4.2.7 on 2024-04-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_alter_publication_is_active_alter_publication_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='session_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='идентификатор сессии оплаты'),
        ),
    ]
