# Generated by Django 4.2.7 on 2024-04-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_publication_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='session_id',
        ),
        migrations.AddField(
            model_name='publication',
            name='payment_session_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='идентификатор сессии оплаты'),
        ),
    ]
