# Generated by Django 4.2.7 on 2024-04-14 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_remove_publication_session_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='payment_session_id',
        ),
    ]
